name: Workflow for Codecov Spring Boot with JaCoCo
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests with JaCoCo
        run: mvn -B test jacoco:report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # - name: SonarQube Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     mvn sonar:sonar \
      #       -Dsonar.projectKey=Learning-Developement-engineering_Calculator-Application\
      #       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
      #       -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      # # - name: Upload coverage to Codecov
      # #   uses: codecov/codecov-action@v5
      # #   env:
      # #     CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
